services:
  petclinic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petclinic
    volumes:
      - ./var/log:/var/log/
    ports:
      - "8080:8080"
      - "9404:9404"
    networks:
      - monitoring

  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - monitoring
    depends_on:
      - petclinic

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus
      - loki
  
  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    command:
      - "--config.file=/etc/loki/local-config.yaml"
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml
      - ./loki:/loki
      - ./loki/wal:/wal
    networks:
      - monitoring
  
  promtail:
    image: grafana/promtail
    container_name: promtail
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./var/log:/var/log/
    command:
      - "--config.file=/etc/promtail/promtail-config.yml"
    networks:
      - monitoring
    depends_on:
      - loki

networks:
  monitoring:
    driver: bridge